### ISSUE TITLE
Redirect old urls to new

### ISSUE THREAD

**Issue by lukasoppermann** [primer/design#389]
With the new IA some old urls need to be redirected to new ones.

## Octicons
- https://primer.style/octicons/ → https://primer.style/foundations/icons/
- https://primer.style/octicons/guidelines/design → https://primer.style/foundations/icons/design-guidelines
- https://primer.style/octicons/:icon-name → https://primer.style/foundations/icons/:icon-name

**Comment by rezrah** [comment]
From @colebemis in https://github.com/primer/octicons/pull/916#issuecomment-1419646661


- https://primer.style/octicons/packages/ruby → https://github.com/primer/octicons/tree/main/lib/octicons_gem#readme
- https://primer.style/octicons/packages/jekyll → https://github.com/primer/octicons/tree/main/lib/octicons_jekyll#readme
- https://primer.style/octicons/packages/javascript → https://github.com/primer/octicons/tree/main/lib/octicons_node#readme
- https://primer.style/octicons/packages/react → https://github.com/primer/octicons/tree/main/lib/octicons_react#readme
- https://primer.style/octicons/packages/styled-system →  https://github.com/primer/octicons/tree/main/lib/octicons_styled#readme

**Comment by rezrah** [comment]
Redirects are ready for testing.

In the following examples, you can assume that `https://primerstyle-staging.azurewebsites.net` is equivalent to `https://primer.style`. 

- https://primerstyle-staging.azurewebsites.net/octicons/guidelines/design/
- https://primerstyle-staging.azurewebsites.net/octicons/packages/ruby/
- https://primerstyle-staging.azurewebsites.net/octicons/packages/javascript/
- https://primerstyle-staging.azurewebsites.net/octicons/packages/jekyll/
- https://primerstyle-staging.azurewebsites.net/octicons/packages/styled-system/
- https://primerstyle-staging.azurewebsites.net/octicons/packages/react/
- https://primerstyle-staging.azurewebsites.net/octicons/accessibility-inset-16


☝ All of these should redirect to their new locations instead of 404. 

@emilybrick @lukasoppermann have I missed any? Otherwise, I'll go ahead and make these active on primer.style.
